// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqhjpgovlqvdiuhyxmsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaGpwZ292bHF2ZGl1aHl4bXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzExNzcsImV4cCI6MjA2ODcwNzE3N30.pV8kuzQ431tyRyoIVvKI3Z_pCuGTDNpnesOmvvmxuaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});